- Simplified preprocessor's choice by eliminating Solaris' possibility. If the preprocessor is not found. An error message will be issued without further attempts to look for other C preprocessors. - Ported the whole script into csh
git-svn-id: file:///Users/andre/andre_msc/trunk/calo-preproc@147 b2e9302d-b4d2-0310-80c4-8586bce995ec

diff --git a/dist/spec/src/genspec b/dist/spec/src/genspec
--- a/dist/spec/src/genspec
+++ b/dist/spec/src/genspec
@@ -1,51 +1,42 @@
-#!/bin/sh
+#!/bin/csh -f
 
 #
 # path of the C preprocessor
 #
-CPP="/usr/ccs/lib/cpp"
+set CPPFLAGS=" -x c-header -E"
+set CPPNAME=`which gcc`
+set CPP="$CPPNAME$CPPFLAGS"
 
 #
 # check argument count
 #
-if [ $# != 4 ] 
-then
+if ( $# != 4 ) then
   echo "usage : genspec basename language path-to-parser"
   exit 1
-fi
+endif
 
 #
 # path of the test_parser program
 #
-PARSER="$4"
+set PARSER="$4"
 
 #
 # check if CPP can be found
 #
-if [ ! -x $CPP ] 
-then
-
-  # try GNU compiler instead
-
-  if which gcc
-  then
-    CPP="gcc -x c-header -E"
-  else
-    echo "genspec: cannot find preprocessor: $CPP"
-    echo "genspec: set CPP variable in genspec script"
-    exit 1
-  fi
-fi
+if ( `filetest -x $CPPNAME` == 0 ) then
+  echo "genspec: cannot find preprocessor: $CPP"
+  echo "genspec: set CPP variable in genspec script"
+  exit 1
+endif
 
 #
 # check if PARSER can be found
 #
-if [ ! -x $PARSER ] 
-then
+if ( `filetest -x $PARSER` == 0 ) then
   echo "genspec: cannot find parser"
   echo "genspec: set PARSER variable in genspec script"
   exit 1
-fi
+endif
 
 #
 # call parser
